// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _cordiccart2pol_HH_
#define _cordiccart2pol_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "cordiccart2pol_fadEe.h"
#include "cordiccart2pol_faeOg.h"
#include "cordiccart2pol_fmfYi.h"
#include "cordiccart2pol_fdg8j.h"
#include "cordiccart2pol_fchbi.h"
#include "cordiccart2pol_Kvbkb.h"
#include "cordiccart2pol_ancud.h"

namespace ap_rtl {

struct cordiccart2pol : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > x;
    sc_in< sc_lv<32> > y;
    sc_out< sc_lv<32> > r;
    sc_out< sc_logic > r_ap_vld;
    sc_out< sc_lv<32> > theta;
    sc_out< sc_logic > theta_ap_vld;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const2;
    sc_signal< sc_lv<32> > ap_var_for_const1;
    sc_signal< sc_lv<5> > ap_var_for_const3;


    // Module declarations
    cordiccart2pol(sc_module_name name);
    SC_HAS_PROCESS(cordiccart2pol);

    ~cordiccart2pol();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    cordiccart2pol_Kvbkb* Kvalues_U;
    cordiccart2pol_ancud* angles_U;
    cordiccart2pol_fadEe<1,5,32,32,32>* cordiccart2pol_fadEe_U1;
    cordiccart2pol_faeOg<1,5,32,32,32>* cordiccart2pol_faeOg_U2;
    cordiccart2pol_fmfYi<1,4,32,32,32>* cordiccart2pol_fmfYi_U3;
    cordiccart2pol_fmfYi<1,4,32,32,32>* cordiccart2pol_fmfYi_U4;
    cordiccart2pol_fmfYi<1,4,32,32,32>* cordiccart2pol_fmfYi_U5;
    cordiccart2pol_fdg8j<1,16,32,32,32>* cordiccart2pol_fdg8j_U6;
    cordiccart2pol_fchbi<1,2,32,32,1>* cordiccart2pol_fchbi_U7;
    cordiccart2pol_fchbi<1,2,32,32,1>* cordiccart2pol_fchbi_U8;
    sc_signal< sc_lv<33> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > Kvalues_address0;
    sc_signal< sc_logic > Kvalues_ce0;
    sc_signal< sc_lv<32> > Kvalues_q0;
    sc_signal< sc_lv<4> > angles_address0;
    sc_signal< sc_logic > angles_ce0;
    sc_signal< sc_lv<32> > angles_q0;
    sc_signal< sc_lv<32> > grp_fu_166_p2;
    sc_signal< sc_lv<32> > reg_200;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<32> > grp_fu_171_p2;
    sc_signal< sc_lv<32> > reg_206;
    sc_signal< sc_lv<1> > grp_fu_187_p2;
    sc_signal< sc_lv<1> > tmp_1_reg_461;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > grp_fu_193_p2;
    sc_signal< sc_lv<1> > tmp_6_reg_466;
    sc_signal< sc_lv<32> > select_ln24_fu_325_p3;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > select_ln24_1_fu_338_p3;
    sc_signal< sc_lv<32> > select_ln24_2_fu_354_p3;
    sc_signal< sc_lv<5> > i_fu_368_p2;
    sc_signal< sc_lv<5> > i_reg_489;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > icmp_ln39_fu_362_p2;
    sc_signal< sc_lv<1> > icmp_ln41_fu_398_p2;
    sc_signal< sc_lv<1> > icmp_ln41_reg_504;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > icmp_ln41_1_fu_404_p2;
    sc_signal< sc_lv<1> > icmp_ln41_1_reg_509;
    sc_signal< sc_lv<1> > tmp_10_reg_514;
    sc_signal< sc_lv<32> > factor_reg_519;
    sc_signal< sc_lv<32> > angles_load_reg_525;
    sc_signal< sc_lv<32> > select_ln46_fu_419_p3;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > grp_fu_176_p2;
    sc_signal< sc_lv<32> > tmp_3_reg_537;
    sc_signal< sc_lv<32> > grp_fu_155_p2;
    sc_signal< sc_lv<32> > theta1_reg_542;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_lv<32> > grp_fu_161_p2;
    sc_signal< sc_lv<32> > temp_cos_reg_114;
    sc_signal< sc_lv<32> > currenty_2_reg_124;
    sc_signal< sc_lv<32> > theta1_2_reg_134;
    sc_signal< sc_lv<5> > i_0_reg_144;
    sc_signal< sc_lv<64> > zext_ln42_fu_374_p1;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<32> > grp_fu_180_p2;
    sc_signal< sc_logic > ap_CS_fsm_state33;
    sc_signal< sc_lv<32> > grp_fu_155_p0;
    sc_signal< sc_lv<32> > grp_fu_155_p1;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<32> > grp_fu_166_p0;
    sc_signal< sc_lv<32> > grp_fu_166_p1;
    sc_signal< sc_lv<32> > grp_fu_171_p0;
    sc_signal< sc_lv<32> > grp_fu_171_p1;
    sc_signal< sc_lv<32> > grp_fu_176_p0;
    sc_signal< sc_lv<32> > grp_fu_187_p0;
    sc_signal< sc_lv<32> > bitcast_ln16_fu_212_p1;
    sc_signal< sc_lv<8> > tmp_fu_215_p4;
    sc_signal< sc_lv<23> > trunc_ln16_fu_225_p1;
    sc_signal< sc_lv<1> > icmp_ln16_1_fu_235_p2;
    sc_signal< sc_lv<1> > icmp_ln16_fu_229_p2;
    sc_signal< sc_lv<1> > or_ln16_fu_241_p2;
    sc_signal< sc_lv<32> > bitcast_ln24_fu_252_p1;
    sc_signal< sc_lv<8> > tmp_5_fu_255_p4;
    sc_signal< sc_lv<23> > trunc_ln24_fu_265_p1;
    sc_signal< sc_lv<1> > icmp_ln24_1_fu_275_p2;
    sc_signal< sc_lv<1> > icmp_ln24_fu_269_p2;
    sc_signal< sc_lv<1> > or_ln24_fu_281_p2;
    sc_signal< sc_lv<32> > xor_ln33_fu_292_p2;
    sc_signal< sc_lv<32> > xor_ln26_fu_302_p2;
    sc_signal< sc_lv<1> > and_ln16_fu_247_p2;
    sc_signal< sc_lv<32> > currentx_fu_308_p1;
    sc_signal< sc_lv<1> > and_ln24_fu_287_p2;
    sc_signal< sc_lv<1> > or_ln24_1_fu_319_p2;
    sc_signal< sc_lv<32> > select_ln16_fu_312_p3;
    sc_signal< sc_lv<32> > select_ln16_1_fu_332_p3;
    sc_signal< sc_lv<32> > currenty_fu_298_p1;
    sc_signal< sc_lv<32> > select_ln16_2_fu_346_p3;
    sc_signal< sc_lv<32> > bitcast_ln41_fu_380_p1;
    sc_signal< sc_lv<8> > tmp_9_fu_384_p4;
    sc_signal< sc_lv<23> > trunc_ln41_fu_394_p1;
    sc_signal< sc_lv<1> > or_ln41_fu_410_p2;
    sc_signal< sc_lv<1> > and_ln41_fu_414_p2;
    sc_signal< sc_lv<32> > bitcast_ln54_fu_430_p1;
    sc_signal< sc_lv<32> > xor_ln54_fu_434_p2;
    sc_signal< sc_lv<2> > grp_fu_155_opcode;
    sc_signal< sc_lv<5> > grp_fu_187_opcode;
    sc_signal< sc_lv<33> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<33> ap_ST_fsm_state1;
    static const sc_lv<33> ap_ST_fsm_state2;
    static const sc_lv<33> ap_ST_fsm_state3;
    static const sc_lv<33> ap_ST_fsm_state4;
    static const sc_lv<33> ap_ST_fsm_state5;
    static const sc_lv<33> ap_ST_fsm_state6;
    static const sc_lv<33> ap_ST_fsm_state7;
    static const sc_lv<33> ap_ST_fsm_state8;
    static const sc_lv<33> ap_ST_fsm_state9;
    static const sc_lv<33> ap_ST_fsm_state10;
    static const sc_lv<33> ap_ST_fsm_state11;
    static const sc_lv<33> ap_ST_fsm_state12;
    static const sc_lv<33> ap_ST_fsm_state13;
    static const sc_lv<33> ap_ST_fsm_state14;
    static const sc_lv<33> ap_ST_fsm_state15;
    static const sc_lv<33> ap_ST_fsm_state16;
    static const sc_lv<33> ap_ST_fsm_state17;
    static const sc_lv<33> ap_ST_fsm_state18;
    static const sc_lv<33> ap_ST_fsm_state19;
    static const sc_lv<33> ap_ST_fsm_state20;
    static const sc_lv<33> ap_ST_fsm_state21;
    static const sc_lv<33> ap_ST_fsm_state22;
    static const sc_lv<33> ap_ST_fsm_state23;
    static const sc_lv<33> ap_ST_fsm_state24;
    static const sc_lv<33> ap_ST_fsm_state25;
    static const sc_lv<33> ap_ST_fsm_state26;
    static const sc_lv<33> ap_ST_fsm_state27;
    static const sc_lv<33> ap_ST_fsm_state28;
    static const sc_lv<33> ap_ST_fsm_state29;
    static const sc_lv<33> ap_ST_fsm_state30;
    static const sc_lv<33> ap_ST_fsm_state31;
    static const sc_lv<33> ap_ST_fsm_state32;
    static const sc_lv<33> ap_ST_fsm_state33;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_3FD2C90A;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<32> ap_const_lv32_80000000;
    static const sc_lv<32> ap_const_lv32_3FC90FDB;
    static const sc_lv<32> ap_const_lv32_BFC90FDB;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<32> ap_const_lv32_3F800000;
    static const sc_lv<32> ap_const_lv32_BF800000;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_3;
    static const sc_lv<5> ap_const_lv5_4;
    static const sc_lv<5> ap_const_lv5_5;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const3();
    void thread_ap_clk_no_reset_();
    void thread_Kvalues_address0();
    void thread_Kvalues_ce0();
    void thread_and_ln16_fu_247_p2();
    void thread_and_ln24_fu_287_p2();
    void thread_and_ln41_fu_414_p2();
    void thread_angles_address0();
    void thread_angles_ce0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state33();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_bitcast_ln16_fu_212_p1();
    void thread_bitcast_ln24_fu_252_p1();
    void thread_bitcast_ln41_fu_380_p1();
    void thread_bitcast_ln54_fu_430_p1();
    void thread_currentx_fu_308_p1();
    void thread_currenty_fu_298_p1();
    void thread_grp_fu_155_opcode();
    void thread_grp_fu_155_p0();
    void thread_grp_fu_155_p1();
    void thread_grp_fu_166_p0();
    void thread_grp_fu_166_p1();
    void thread_grp_fu_171_p0();
    void thread_grp_fu_171_p1();
    void thread_grp_fu_176_p0();
    void thread_grp_fu_187_opcode();
    void thread_grp_fu_187_p0();
    void thread_i_fu_368_p2();
    void thread_icmp_ln16_1_fu_235_p2();
    void thread_icmp_ln16_fu_229_p2();
    void thread_icmp_ln24_1_fu_275_p2();
    void thread_icmp_ln24_fu_269_p2();
    void thread_icmp_ln39_fu_362_p2();
    void thread_icmp_ln41_1_fu_404_p2();
    void thread_icmp_ln41_fu_398_p2();
    void thread_or_ln16_fu_241_p2();
    void thread_or_ln24_1_fu_319_p2();
    void thread_or_ln24_fu_281_p2();
    void thread_or_ln41_fu_410_p2();
    void thread_r();
    void thread_r_ap_vld();
    void thread_select_ln16_1_fu_332_p3();
    void thread_select_ln16_2_fu_346_p3();
    void thread_select_ln16_fu_312_p3();
    void thread_select_ln24_1_fu_338_p3();
    void thread_select_ln24_2_fu_354_p3();
    void thread_select_ln24_fu_325_p3();
    void thread_select_ln46_fu_419_p3();
    void thread_theta();
    void thread_theta_ap_vld();
    void thread_tmp_5_fu_255_p4();
    void thread_tmp_9_fu_384_p4();
    void thread_tmp_fu_215_p4();
    void thread_trunc_ln16_fu_225_p1();
    void thread_trunc_ln24_fu_265_p1();
    void thread_trunc_ln41_fu_394_p1();
    void thread_xor_ln26_fu_302_p2();
    void thread_xor_ln33_fu_292_p2();
    void thread_xor_ln54_fu_434_p2();
    void thread_zext_ln42_fu_374_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
